name: Android 14 5.15
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      susfs_branch:
        required: false
        type: string
      version:
        required: false
        type: string
      use_zram:
        required: true
        type: boolean
      use_kpm:
        required: false
        type: boolean

jobs:
  build-kernel-a14-5-15-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "131"
          #  os_patch_level: "2023-11"
          #- sub_level: "137"
          #  os_patch_level: "2024-01"
          #- sub_level: "144"
          #  os_patch_level: "2024-03"
          #- sub_level: "148"
          #  os_patch_level: "2024-05"
          #- sub_level: "153"
          #  os_patch_level: "2024-07"
          #- sub_level: "158"
          #  os_patch_level: "2024-08"
          #- sub_level: "167"
          #  os_patch_level: "2024-11"
          #- sub_level: "170"
          #  os_patch_level: "2025-01"
          #- sub_level: "178"
          #  os_patch_level: "2025-03"
          #- sub_level: "180"
          #  os_patch_level: "2025-05"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      susfs_branch: ${{ inputs.susfs_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
