name: Android 15 6.6
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      susfs_branch:
        required: false
        type: string
      version:
        required: false
        type: string
      use_zram:
        required: true
        type: boolean
      use_kpm:
        required: false
        type: boolean


jobs:
  build-kernel-a15-6-6-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "30"
          #  os_patch_level: "2024-08"
          # - sub_level: "46"
          #   os_patch_level: "2024-09"
          - sub_level: "50"
            os_patch_level: "2024-10"
          #- sub_level: "56"
          #  os_patch_level: "2024-11"
          #- sub_level: "57"
          #  os_patch_level: "2024-12"
          #- sub_level: "58"
          #  os_patch_level: "2025-01"
          - sub_level: "66"
            os_patch_level: "2025-02"
          #- sub_level: "77"
          #  os_patch_level: "2025-03"
          #- sub_level: "82"
          #  os_patch_level: "2025-04"
          #- sub_level: "87"
          #  os_patch_level: "2025-05"
          - sub_level: "102"
            os_patch_level: "2025-10"
          #- sub_level: "X"
          #  os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      android_version: "android15"
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      susfs_branch: ${{ inputs.susfs_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
